### PR TITLE
Add link for KituraLimiter to the "Other Middlewares" section of the API docs

### PR DESCRIPTION
**Pull request by teechap**
Not sure if you guys accept pull requests from people outside IBM, but I made a `SwiftRedis`-based middleware to rate limit client requests. You can check out my repo [here](https://github.com/teechap/kitura-limiter). Is there any interest in merging a link to it on kitura.io? Someone might find it useful 👍

### CODE REVIEW

**Comment by ianpartridge** [comment]
Hi @teechap yes we do welcome PRs and I'd be happy to merge this.  We do need a [CLA](https://github.com/IBM-Swift/CLA) though - this is a one-time thing.  Would you be willing to email one to us?  Thanks!

**Comment by teechap** [comment]
Sure, I'll email you the CLA later today...

**Comment by teechap** [comment]
@ianpartridge it says to physically mail the CLA--I don't see an email. What email should I send the scanned CLA to?

**Comment by teechap** [comment]
@ianpartridge oops, I just saw the email. My bad!

**Comment by ianpartridge** [comment]
Thanks!

**Pull request merged**
