### PR TITLE
Update the learn page to ensure users can bookmark the docs

### PR DESCRIPTION
**Pull request by ddunn2**
This PR removes the usage of iFrames as a short term solution.

### CODE REVIEW

**Comment by Andrew-Lees11** [comment]
I had to make a couple of extra changes so we can merge this guide:
- Added the link back to the KITURA DOCS in the top left so you can return to the main website
- Added the links to the docks back to Kuery and JWT so the toggles work
- Added links the the new SSL guide for all the pages

There is an issue introduced by this PR where for the guides with large code blocks  (E.G.) you got a scroll bar for the page. If you scroll the side bar goes over the text. I will raise this as an issue to be fixed at a later date.

**Comment by Andrew-Lees11** [comment]
Another issue is that we lose our place in the menu with the new system. Overall This change does make our webpage look worse so it might be worth trying to solve these problems before we merge.

**Comment by ddunn2** [comment]
@Andrew-Lees11 I'm aware about the `losing our place` issue, but this is a short term solution the alternative is to have docs that we can't link too. 

I don't think this change makes the webpage look worse, given aesthetically it should look the same. The sidebar doesn't retain its current functionality and the time it would take to to fix it would be better spent working on the long term solution. This page is in beta and in my opinion having pages you can't link to is worse than having a sidebar that doesn't remain expanded after clicking a link. 

I am working on a better solution to this issue now, that is using React for our learn page.

**Comment by Andrew-Lees11** [comment]
Now you have fixed the width issue I agree that the loss of the sidebar is worth it for remembering where you. I am happy for you to merge when you are ready.

**Comment by ddunn2** [comment]
Made a last change to fix some font sizing issues caused by this change, and now merging.

**Pull request merged**
